AppCoder/urls.py
from django.urls import path, include
from AppCoder import views
from django.contrib.auth.views import LogoutView

app_name = 'AppCoder'


urlpatterns = [
    path('', views.inicio, name='Inicio'),
    path('cursos', views.cursos, name='Cursos'),
    path('profesores', views.profesores, name='Profesores'),
    path('estudiantes', views.estudiantes, name='Estudiantes'),
    path('entregables', views.entregables, name='Entregables'),
    #path('cursoFormulario', views.cursoFormulario, name='CursoFormulario'),
    path('profesorFormulario', views.profesorFormulario, name='ProfesorFormulario'),
    path('busquedaCamada', views.busquedaCamada, name='BusquedaCamada'),
    path('buscar/', views.buscar),
    path('leerCursos', views.leerCursos, name="LeerCursos"),
    path('curso/list', views.CursoList.as_view(), name='List'),
    path('<int:pk>', views.CursoDetalle.as_view(), name='Detail'),
    path('nuevo', views.CursoCreacion.as_view(), name='New'),
    path('editar/<int:pk>', views.CursoUpdate.as_view(), name='Edit'),
    path('borrar/<int:pk>', views.CursoDelete.as_view(), name='Delete'),
    path('leerProfesores', views.leerProfesores, name='LeerProfesores'),
    path('eliminarProfesor/<profesor_nombre>/',views.eliminarProfesor, name="EliminarProfesor"),
    path('editarProfesor/<profesor_nombre>', views.editarProfesor, name='EditarProfesor'),
    path('login', views.login_request, name='Login'),
    path('register', views.register, name='Registro'),
    path('logout', LogoutView.as_view(template_name='logout.html'), name='Logout'),
    path('editarPerfil', views.editarPerfil, name='EditarPerfil'),
    path('agregarAvatar', views.agregarAvatar, name='AgregarAvatar'),
]

ProyectoCoder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppCoder.urls')),
    path('registro/', include('django.contrib.auth.urls')),
    path('registro/', include('registro.urls')),   
]

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

registro/urls.py
from django.urls import path
from .views import RegistroPagina, UsuarioEdicion

urlpatterns = [
    path('register/', RegistroPagina.as_view(),name='register'), 
    path('editar/', UsuarioEdicion.as_view(), name='editar'),
    
    
]

AppCoder/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Curso(models.Model):
    nombre=models.CharField(max_length=40)
    camada=models.IntegerField()

    def __str__(self):
        return f"Nombre: {self.nombre} - Camada: {self.camada}"

class Estudiante(models.Model):
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    email = models.EmailField()

class Profesor(models.Model):
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    email = models.EmailField()
    profesion = models.CharField(max_length=30)

    def __str__(self):
        return f"Nombre: {self.nombre} - Apellido: {self.apellido} - Email: {self.email} - Profesión: {self.profesion}"

class Entregable(models.Model):
    nombre = models.CharField(max_length=30)
    fechaDeEntrega = models.DateField()
    entregado = models.BooleanField()
   
class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='avatares', null=True, blank=True)

registro/models.py
from django.db import models

# Create your models here.

AppCoder/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CursoFormulario(forms.Form):
    nombre = forms.CharField()
    camada = forms.IntegerField()

class ProfesorFormulario(forms.Form):
    nombre = forms.CharField(max_length=30)
    apellido = forms.CharField(max_length=30)
    email = forms.EmailField()
    profesion = forms.CharField(max_length=30)

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repetir contraseña', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {k:"" for k in fields}

class UserEditForm(UserCreationForm):
    email = forms.EmailField(label="Ingrese su email:")
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repetir la contraseña', widget=forms.PasswordInput)

    last_name = forms.CharField()
    first_name = forms.CharField()

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2', 'last_name', 'first_name']
        help_texts = {k:"" for k in fields}

class AvatarFormulario(forms.Form):
    #especificar los campos
    username=forms.ModelChoiceField(queryset=User.objects.all())
    imagen = forms.ImageField(required=True)

    class Meta:
        model = User
        fields = ['imagen']
        help_texts = {k:"" for k in fields}

registro/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, PasswordChangeForm
from django import forms
from django.contrib.auth.models import User 



class FormularioRegistroUsuario(UserCreationForm):
    first_name = forms.CharField(max_length=20, label='Nombre', widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(max_length=20, label='Apellido', widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    username = forms.CharField(max_length=20, label='Usuario', widget=forms.TextInput(attrs={'class':'form-control'}))
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(label='Repita Contraseña', widget=forms.PasswordInput(attrs={'class':'form-control'}))
    
    class Meta:
        model = User
        fields = ('email', 'username', 'first_name', 'last_name', 'password1', 'password2')


class FormularioEdicion(UserChangeForm):
    password = None
    email = forms.CharField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(max_length=20, label='Nombre', widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(max_length=20, label='Apellido', widget=forms.TextInput(attrs={'class':'form-control'}))
    username = forms.CharField(max_length=20, label='Usuario', widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model = User
        fields = ('email', 'username', 'first_name', 'last_name')

AppCoder/views.py
from django.shortcuts import render
from AppCoder.models import Curso, Profesor, Avatar, User
from django.http import HttpResponse
from AppCoder.forms import CursoFormulario, ProfesorFormulario
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout, authenticate
from AppCoder.forms import UserRegisterForm, UserEditForm, AvatarFormulario
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password

@login_required
def inicio(request):
    avatares = Avatar.objects.filter(user=request.user.id)
    print(avatares[0].imagen.url)
    return render(request, 'inicio.html', {'url':avatares[0].imagen.url})

def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data = request.POST)
        if form.is_valid():
            usuario = form.cleaned_data.get('username')
            contras = form.cleaned_data.get('password')

            user = authenticate(username=usuario, password=contras)
            if user is not None:
                login(request, user)
                return render(request, "inicio.html", {"mensaje":f"Bienvenido {usuario}"})
            else:
                return render(request, "inicio.html", {"mensaje":"Error, datos incorrectos."})
        else:
            return render(request, "inicio.html", {"mensaje":"Error, formulario erroneo."})
    form = AuthenticationForm()
    return render(request, "login.html", {"form":form})

def register(request):
    if request.method == 'POST':
        #form = UserCreationForm(request.POST)
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            form.save()
            return render(request, 'inicio.html', {'mensaje':'Usuario Creado :)'})
    else:
        #form = UserCreationForm()
        form = UserRegisterForm()
    return render(request, 'registro.html', {'form':form})

#def inicio(request):
#    return render(request, 'inicio.html')

#def cursos(request):
#    return render(request, 'cursos.html')

def profesores(request):
    return render(request, 'profesores.html')

def estudiantes(request):
    return render(request, 'estudiantes.html')

def entregables(request):
    return render(request, 'entregables.html')

def cursos(request):
    if request.method == 'POST':
        miFormulario = CursoFormulario(request.POST)

        print(miFormulario)

        if miFormulario.is_valid:

            informacion = miFormulario.cleaned_data
            
            curso = Curso(nombre=informacion['nombre'], camada=informacion['camada'])
            curso.save()

            return render(request, 'inicio.html')
    else:
        miFormulario = CursoFormulario()
    
    return render(request, 'cursos.html', {'miFormulario':miFormulario})

def profesorFormulario(request):
    if request.method == 'POST':
        miFormulario = ProfesorFormulario(request.POST)

        print(miFormulario)

        if miFormulario.is_valid:

            informacion = miFormulario.cleaned_data
            
            profesor = Profesor(nombre=informacion['nombre'], 
                                apellido=informacion['apellido'], 
                                email=informacion['email'],
                                profesion=informacion['profesion'])
            profesor.save()

            return render(request, 'inicio.html')
    else:
        miFormulario = ProfesorFormulario()
    
    return render(request, 'ProfesorFormulario.html', {'miFormulario':miFormulario})

def busquedaCamada(request):
    return render(request, 'busquedaCamada.html')

def buscar(request):
    if request.GET['camada']:
        camada = request.GET['camada']
        curso = Curso.objects.filter(camada__icontains=camada)

        return render(request, 'inicio.html', {"cursos":curso, "camada":camada})
    else:
        respuesta = "No enviaste datos."

    #return HttpResponse(respuesta)
    return render(request, 'inicio.html', {"respuesta":respuesta})

def leerCursos(request):
    cursos = Curso.objects.all()
    contexto = {"cursos":cursos}
    return render(request, "leerCursos.html", contexto)

def leerProfesores(request):
    profesores = Profesor.objects.all()
    contexto = {"profesores":profesores}
    return render(request, "leerProfesores.html", contexto)

def eliminarProfesor(request, profesor_nombre):
    profesor = Profesor.objects.get(nombre=profesor_nombre)
    profesor.delete()

    profesores = Profesor.objects.all()
    contexto = {"profesores":profesores}
    return render(request, "leerProfesores.html", contexto)

def editarProfesor(request, profesor_nombre):
    profesor = Profesor.objects.get(nombre=profesor_nombre)
    if request.method == 'POST':
        miFormulario = ProfesorFormulario(request.POST)
        print(miFormulario)

        if miFormulario.is_valid:
            informacion = miFormulario.cleaned_data

            profesor.nombre = informacion['nombre']
            profesor.apellido = informacion['apellido']
            profesor.email = informacion['email']
            profesor.profesion = informacion['profesion']

            profesor.save()
            return render(request, "inicio.html")
    else:
        miFormulario = ProfesorFormulario(initial={'nombre':profesor.nombre, 
                                                   'apellido':profesor.apellido, 
                                                   'email':profesor.email, 
                                                   'profesion':profesor.profesion})
    return render(request, "editarProfesor.html", 
                  {"miFormulario":miFormulario, "profesor_nombre":profesor_nombre})

@login_required
def editarPerfil(request):
    usuario = request.user 
    if request.method == 'POST':
        miFormulario = UserEditForm(request.POST)
        print(miFormulario)
        if miFormulario.is_valid():
            informacion = miFormulario.cleaned_data
            print(miFormulario)
            usuario.email = informacion['email']
            usuario.first_name = informacion['first_name']
            usuario.last_name = informacion['last_name']
            if informacion['password1'] == informacion['password2']:
                usuario.password = make_password(informacion['password1'])
                usuario.save()
            else:
                return render(request, 'inicio.html', {'mensaje':'Contraseña incorrecta.'})

            return render(request, 'inicio.html')
    else:
        miFormulario = UserEditForm(initial={'email':usuario.email})

    return render(request, "editarPerfil.html", {"miFormulario":miFormulario, "usuario":usuario})

@login_required
def agregarAvatar(request):
    if request.method == 'POST':
        miFormulario = AvatarFormulario(request.POST, request.FILES)
        if miFormulario.is_valid():
            u = User.objects.get(username=request.user)
            avatar = Avatar(user=u, imagen=miFormulario.cleaned_data['imagen'])
            avatar.save()

            return render(request, 'inicio.html')
    else:
        miFormulario = AvatarFormulario()
    return render(request, 'agregarAvatar.html', {'miFormulario':miFormulario})

class CursoList(ListView):
    model = Curso
    template_name = "cursos_list.html"

class CursoDetalle(DetailView):
    model = Curso
    template_name = "curso_detalle.html"

class CursoCreacion(CreateView):
    model = Curso
    template_name = "cursos_form.html"
    success_url = reverse_lazy("AppCoder:List")
    fields = ['nombre', 'camada']

class CursoUpdate(UpdateView):
    model = Curso
    success_url = "/AppCoder/curso/list"
    template_name = "cursos_form.html"
    fields = ['nombre', 'camada']

class CursoDelete(DeleteView):
    model = Curso
    template_name = "curso_confirm_delete.html"
    success_url = "/AppCoder/curso/list"

registro/views.py
from django.views.generic import  UpdateView
from django.views.generic.edit import  UpdateView, FormView
from django.contrib.auth import login
from django.shortcuts import redirect
from django.urls import reverse_lazy
from .forms import FormularioRegistroUsuario, FormularioEdicion

class RegistroPagina(FormView):
    template_name = 'registration/register.html'
    form_class = FormularioRegistroUsuario
    redirect_autheticated_user = True
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegistroPagina, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('login')
        return super(RegistroPagina, self).get(*args, **kwargs)

class UsuarioEdicion(UpdateView):
    form_class = FormularioEdicion
    template_name= 'registration/editar.html'
    success_url = reverse_lazy('home')

    def get_object(self):
        return self.request.user

AppCoder/templates/agregarAvatar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>Cargar avatar</h3>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ miFormulario.as_p }}
        <input type="submit" value="Actualizar">
    </form>
</body>
</html>

AppCoder/templates/cursoFormulario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario - Agregar Curso</title>
</head>
<body>
    {% extends "AppCoder/padre.html" %}

    {% load static %}
    
    {% if miFormulario.errors %}
    <p style="color:red;"> Están mal los datos, revisar. </p>
    {% endif %}

    <form action="cursoFormulario" method="POST">{% csrf_token %}
        
        <table>
            {{ miFormulario.as_table }}
        </table>
        
        <input type="submit" value="Enviar">
    </form>
</body>
</html>

AppCoder/templates/curso_detalle.html
AppCoder:<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Curso - Detalle</title>
</head>
<body>
    <p>Nombre del Curso: <i>{{ curso.nombre }}</i></p>
    <p>Camada: <i>{{ curso.camada }}</i></p>
    <P>
        <a href="{% url 'AppCoder:List' %}">Regresar</a>
    </P>
</body>
</html>

AppCoder/templates/curso_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Curso - Formulario</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="Enviar" />
    </form>
</body>
</html>

AppCoder/templates/cursos.html
{% extends 'padre.html' %}

{% load static %}

{% block contenidoQueCambia %}

    <!-- colocamos lo que va a cambiar -->
    <h1>Cursos</h1>
    {% if miFormulario.errors %}
    <p style="color:red;"> Están mal los datos, revisar. </p>
    {% endif %}

    <form action="" method="POST">{% csrf_token %}
        
        <table>
            {{ miFormulario.as_table }}
        </table>
        
        <input type="submit" value="Enviar">
    </form>

{% endblock %}

AppCoder/templates/cursos_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Curso - Formulario</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="Enviar" />
    </form>
</body>
</html>

AppCoder/templates/cursos_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cursos - Lista</title>
</head>
<body>
    <h1>Cursos de Coder - Python</h1>
    <ul>
        {% for curso in object_list %}
            <li>
                <p>Nombre: {{ curso.nombre }} </p>
                <p>
                    <a href="{% url 'AppCoder:Detail' curso.id %}">Ver</a>
                    <a href="{% url 'AppCoder:Edit' curso.id %}">Editar</a>
                    <a href="{% url 'AppCoder:Delete' curso.id %}">Borrar</a>
                </p>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

AppCoder/templates/entregables.html
{% extends 'padre.html' %}

{% load static %}

{% block contenidoQueCambia %}

    <!-- colocamos lo que va a cambiar -->
    <h1>Entregables</h1>
    <p>Información de las Entregas</p>

{% endblock %}

AppCoder/templates/leerProfesores.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profesores</title>
</head>
<body>
    {% for p in profesores %}
        <li>{{p}}</li>
        <button>
            <a href="{% url 'AppCoder:EliminarProfesor' p.nombre %}">Eliminar</a>
            <a href="{% url 'AppCoder:EditarProfesor' p.nombre %}">Editar</a>
        </button>
    {% endfor %}
    <a href="profesores">Agregar otro Profesor</a>
</body>
</html>

AppCoder/templates/padre.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Proyecto Coder</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'AppCoder/css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'AppCoder/css/bootstrap.min.css' %}" rel="stylesheet" >
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

    </head>
    <body>
        {% if mensaje %}
            <p>{{mensaje}}</p>
        {% endif %}
        <form action="/AppCoder/buscar/" method="GET">
            <p>Realizar búsqueda de camada:</p>
            <input type="number" name="camada" id="camada">
            <input type="submit" value="Buscar">
        </form>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'AppCoder:Inicio' %}">Inicio</a>
                <a class="navbar-brand" href="{% url 'AppCoder:Cursos' %}"> Cursos</a>
                <a class="navbar-brand" href="{% url 'AppCoder:Estudiantes' %}"> Estudiantes</a>
                <a class="navbar-brand" href="{% url 'AppCoder:Profesores' %}"> Profesores</a>
                <a class="navbar-brand" href="{% url 'AppCoder:Entregables' %}"> Entregables</a>
                {% if not request.user.is_authenticated %}
                <a class="btn btn-primary" href="{% url 'AppCoder:Login' %}">Iniciar Sesión</a>
                {% endif %}

                {% if request.user.is_authenticated %}
                
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-expanded="false">
                        <img height="30px" src="{{url}}" />
                        <span class="caret"></span>
                        {{user.username}}
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{% url 'AppCoder:EditarPerfil' %}">Editar Perfil</a>
                        <a class="dropdown-item" href="{% url 'AppCoder:AgregarAvatar' %}">Agregar Avatar</a>
                        <a class="dropdown-item" href="{% url 'AppCoder:Logout' %}">Cerrar Sesión</a>
                    </div>
                </div>
                <!--
                <select name="{{user.username}}" id="{{user.username}}">
                    <option value="{% url 'AppCoder:EditarPerfil' %}">Editar Perfil</option>
                    <option value="{% url 'AppCoder:AgregarAvatar' %}">Agregar Avatar</option>
                    <option value="{% url 'AppCoder:Logout' %}">Cerrar Sesión</option>
                </select>
                
                <p class="text-muted small mb-4 mb-lg-0">Hola {{user.username}}!!!</p>
                <img height="30px" src="{{url}}" />
                <a class="navbar-brand" href="{% url 'AppCoder:EditarPerfil' %}">Editar Perfil</a>
                <a class="navbar-brand" href="{% url 'AppCoder:AgregarAvatar' %}">Agregar Avatar</a>
                <a class="navbar-brand" href="{% url 'AppCoder:Logout' %}">Cerrar Sesión</a>
                -->
                {% endif %}
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">Nuestra web Intermedia!</h1>
                            <h2>Django - CoderHouse</h2>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        <!-- Modificar el contenido de lo que va a cambiar -->
        {% block contenidoQueCambia %}
        {% endblock %}

        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">About</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Contact</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Terms of Use</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Privacy Policy</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; SDi 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'AppCoder/js/scripts.js' %}"></script>
        <script src="{% static 'AppCoder/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'AppCoder/js/popper.min.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>